### ISSUE TITLE
[Feature Request] Support for pre-existing S3 buckets

### ISSUE THREAD

**Issue by hardingmatt** [chankh/lambda-s3-thumbnail#2]
This SAM application is great!

I would like the option to use [s3-thumbnail](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:831212071815:applications~s3-thumbnail) and [s3-image-indexer](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:831212071815:applications~s3-image-indexer) on pre-existing S3 buckets.  But when I specify an S3 bucket name that already exists, the Cloudformation stack creation rolls back with the following error:

> The following resource(s) failed to create: [ImageBucket]. . Rollback requested by user.

Would you be open to adding optional parameters for an existing S3 bucket?  Here's a blog post that is similar to what I'm suggesting: https://alestic.com/2016/11/aws-cloudformation-optional-resources/

Please let me know if I can provide more information.  Thanks!

**Comment by chankh** [comment]
Thank you for your feedback. Do you mind submitting a PR for this?

**Comment by hardingmatt** [comment]
Looks like I was wrong: the [SAM Documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3) states that this is not supported.

```
NOTE: To specify an S3 bucket as an event source for a Lambda function,
both resources have to be declared in the same template. AWS SAM does
not support specifying an existing bucket as an event source.
```

I've added this use case / Feature Request to https://github.com/awslabs/aws-sam-local/issues/206

I will close this Feature Request.
